find_package(SuiteSparse COMPONENTS cxsparse )
set(CSparse_FOUND ${SuiteSparse_FOUND})
set(CSparse_LIBRARIES ${SuiteSparse_LIBRARIES})
set(CSparse_LIBRARY ${SuiteSparse_LIBRARIES})
set(CSparse_INCLUDE_DIRS ${SuiteSparse_INCLUDE_DIRS})

set(CSPARSE_FOUND ${SuiteSparse_FOUND})
set(CSPARSE_LIBRARIES ${SuiteSparse_LIBRARIES})
set(CSPARSE_LIBRARY ${SuiteSparse_LIBRARIES})
set(CSPARSE_INCLUDE_DIRS ${SuiteSparse_INCLUDE_DIRS})