find_path(PROJ4_INCLUDE_DIR NAMES proj_api.h
	PATHS ${CONAN_INCLUDE_DIRS_PROJ}
	NO_DEFAULT_PATH)

find_library(PROJ4_LIBRARY NAMES ${CONAN_LIBS_PROJ}
	PATHS ${CONAN_LIB_DIRS_PROJ}
	NO_DEFAULT_PATH)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(PROJ4
	REQUIRED_VARS PROJ4_LIBRARY PROJ4_INCLUDE_DIR
	FOUND_VAR PROJ4_FOUND
)

set(PROJ4_INCLUDE_DIRS ${PROJ4_INCLUDE_DIR})
set(PROJ4_LIBRARIES ${PROJ4_LIBRARY})

mark_as_advanced(PROJ4_INCLUDE_DIR PROJ4_LIBRARY)
